
server{
    listen 443 ssl;
    server_name zel-yama.42.fr;
    ssl_protocols STLv1.2 STv1.3;
    ssl_certificate  /etc/ssl/nginx/nginx.key;
    ssl_certificate.key /etc/ssl/nginx/nginx.crt

    location / {
        root html;
    }
    #location fastcgi php 
}