

events{

}

http{

    server {
        include mime.types;
        listen 443 ssl;
        server_name zel-yama.42.fr;
   
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_certificate     /etc/ssl/nginx/nginx.crt;
        ssl_certificate_key /etc/ssl/nginx/nginx.key;
        root /srv/www/wordpress;
  
   
     
        location ~ \.php$  {
            include fastcgi_params;
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        }
    }

}