
events{

}

server {
    listen 443 ssl;
    server_name zel-yama.42.fr;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate     /etc/ssl/nginx/nginx.crt;
    ssl_certificate_key /etc/ssl/nginx/nginx.key;

    location / {
      
        root html;
    }
    #location fastcgi php 
}