
services:
    mariadb:
        image: mariadb
        build: requirements/mariadb/
        restart: always
    
        container_name: mariadb
        env_file:
            - .env
        volumes:
            - storage:/var/lib/mysql
        networks:
            - inception
    
    wordpress:
        image: wordpress
        build: requirements/wordpress/
        container_name: wordpress
    
    
        env_file:
            - .env
        
        depends_on:
            - mariadb

        volumes:
            - storage_wordpress:/srv/www/wordpress
        networks:
            - inception
        restart: always
    nginx:
        image: nginx
        container_name: nginx

        build: requirements/nginx/
        
        volumes:
            - storage_wordpress:/srv/www/wordpress
        
        ports:
            - 443:443
        networks:
            - inception
        
        depends_on:
            - wordpress
        restart: always
    
        
networks:
    inception:
        driver: bridge
        
volumes:
    storage:
        driver_opts:
            type: "none"
            o: "bind"
            device: "/home/zel-yama/data/mariadb"
    storage_wordpress:
        driver_opts:
            type: "none"
            o: "bind"
            device: "/home/zel-yama/data/wordpress"