version: "5.1.2"

services:
    mariadb:
        build: srcs/requirements/mariadb/
        restart: always
    
        contianer_name: mariadb
        env_file:
            - .env
        volumes:
            - storage:/val/lib/mysql
        networks:
            - inception
    
    wordpress:
        build: srcs/requirements/wordpress/
    
        restart: always
    
        env_file:
            - .env
        container_name: wordpress
        
        depends_on:
            - mariadb
        volumes:
            - storage:/srv/www/wordpress
        networks:
            - inception
    nginx:
        container_name: nginx
        build: srcs/requirements/nginx/
        
        restart: always
        
        ports:
            - "443:443"
        networks:
            - inception
        
        depends_on:
           - wordpress
        volumes:
            - storage:/srv/www/wordpress
        
networks:
    inception:
        driver: bridge
        
volumes:
    storage:
   
