version: "5.1.2"

services:
    mariadb:
        image: mysql

        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 121
        volumes:
           - ./data:/home/zel-yama
        ports:
            - 3306:3306
